export const COMPANY_STATUS = {
  UNENTERED: '未エントリー',
  ES_DRAFTING: 'ES作成中',
  ES_SUBMITTED: 'ES提出済',
  TEST_WAITING: '適性検査待ち',
  FIRST_INTERVIEW: '1次面接待ち',
  SECOND_INTERVIEW: '2次面接待ち',
  FINAL_INTERVIEW: '最終面接',
  OFFER: '内定',
} as const;

export type CompanyStatus = typeof COMPANY_STATUS[keyof typeof COMPANY_STATUS];

export const STATUS_SORT_ORDER = [
  COMPANY_STATUS.OFFER,
  COMPANY_STATUS.FINAL_INTERVIEW,
  COMPANY_STATUS.SECOND_INTERVIEW,
  COMPANY_STATUS.FIRST_INTERVIEW,
  COMPANY_STATUS.TEST_WAITING,
  COMPANY_STATUS.ES_SUBMITTED,
  COMPANY_STATUS.ES_DRAFTING,
  COMPANY_STATUS.UNENTERED
];
